import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { TodoList } from "../src/components/TodoList";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>To do list</h1>
      <TodoList />
    </div>
  );
};

export default Home;
